name: Pull Request Workflow
on:
  pull_request:
    branches: [ master ]
    types: [opened, synchronize, reopened, labeled]
  push:
    branches: [ master ]

jobs:

  PR-Job:
    runs-on: ubuntu-latest
    steps:
    - run: echo ${{ github.ref }}
    - run: echo ${{ github.sha }}
    - run: echo ${{ github.event_name }}
    - run: echo ${{ toJSON(github.event) }}
    - uses: actions/checkout@v3
    - run: ls
